# Generated by Django 4.2.2 on 2023-07-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fotografia', 'Fotografía'), ('danza', 'Danza'), ('dibujo_y_pintura', 'Dibujo y Pintura'), ('manualidades', 'Manualidades'), ('otro', 'Otro')], default='Fotografía', max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_publish', models.DateTimeField(auto_now_add=True)),
                ('contactNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pics', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Cooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tradicional', 'Tradicional'), ('vegetariana', 'Vegetariana'), ('vegana', 'Vegana'), ('sin_tacc', 'Sin T.A.C.C.'), ('otro', 'Otro')], default='Tradicional', max_length=15)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_publish', models.DateTimeField(auto_now_add=True)),
                ('contactNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pics', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('inveriones', 'Inversiones'), ('contaduria', 'Contaduria'), ('balances', 'Balances'), ('otro', 'Otro')], default='Otro', max_length=15)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_publish', models.DateTimeField(auto_now_add=True)),
                ('contactNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pics', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='HandWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('herreria', 'Herreria'), ('carpinteria', 'Carpintería'), ('plomeria', 'Plomeria'), ('electricidad', 'Electricidad'), ('otro', 'Otro')], default='Otro', max_length=15)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_publish', models.DateTimeField(auto_now_add=True)),
                ('contactNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pics', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ingenieria', 'Ingeniería'), ('arquitectura', 'Arquitectura'), ('telecomunicaciones', 'Telecomunicaciones'), ('otro', 'Otro')], default='Otro', max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_publish', models.DateTimeField(auto_now_add=True)),
                ('contactNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pics', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vuelos', 'Vuelos'), ('actividades', 'Actividades'), ('hospedaje', 'Hospedaje'), ('otro', 'Otro')], default='Otro', max_length=15)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_publish', models.DateTimeField(auto_now_add=True)),
                ('contactNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pics', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
