# Generated by Django 4.2.2 on 2023-07-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='date_publish',
            field=models.DateField(auto_now_add=True),
        ),
    ]
